# Page settings
baseurl = "localhost:1313"
title = "Visualização de Informação"
languageCode = "en-us"
theme = "elate"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Dados sobre Boqueirão"
    home = "Home"
    work = "Dados"


    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Nosso açude e sua escassez."
    subtitle = 'Como nosso açude sobreviveu em tempos de crise'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]


  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Dados"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Periodo de seca"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "A chegada das aguas"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "O fim do racionamento"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"



  # Testimonials section




  # Services section


  # About section

  # Counters section
  [params.counters]
    enable = true
    title = "Estado Atual"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Volume do Açude em %"

      from = 0.0
      to = 9.0
      interval = 0.4
      speed = 50

    [[params.counters.item]]
      description = "Volume do Açude em m/3"
      from = 0
      to = 38150
      interval = 1600
      speed = 500

    [[params.counters.item]]
      description = "Dias da chegada da transposição"
      from = 0
      to = 217
      interval = 1
      speed = 500

    [[params.counters.item]]
      description = "Dias fora do racionamento"
      from = 0
      to = 112
      interval = 1
      speed = 500

  # Contact section


  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
